### PR TITLE
Added a miniboxed attempt :)

### PR DESCRIPTION
**Pull request by VladUreche**
Final numbers:

```
[info] Benchmark                                       Mode  Samples        Score  Score error  Units
[info] r.VecMapBenchmark.squareDoubleArrayWithLoop    thrpt       20  1478640.429    78967.084  ops/s
[info] r.VecMapBenchmark.squareDoubleArrayWithMap     thrpt       20    71711.934     3269.255  ops/s
[info] r.VecMapBenchmark.squareDoubleVec              thrpt       20  1397215.415    17459.019  ops/s
```

and code:

``` scala
package respec

final class Vec[@miniboxed T](elems: MbArray[T]) {
  def size: Int = elems.length
  def apply(i: Int): T = elems(i)
  def map[@miniboxed B](f: T => B): Vec[B] = {
    val a = MbArray.empty[B](elems.length)
    var i = 0
    while (i < elems.length) {
      a(i) = f(elems(i))
      i += 1
    }
    new Vec(a)
  }
}

object Vec {
  def apply[@miniboxed A](elems: Array[A]): Vec[A] = new Vec(MbArray.clone(elems))
}
```

### CODE REVIEW

**Comment by VladUreche** [comment]
Thanks Tom! How about a joint talk at nescala about `MbArrays` and how they solve the unboxing issue without requiring ClassTags? You think that would be interesting?

**Comment by tixxit** [comment]
That talk would be great. I'm not sure if I can commit to a joint talk, just because I'm planning on submitting a (lightning) talk on FpFilter and am already pressed for time with my 9 month old with another on the way :( (also :)). I'd probably be more up for doing something a little less formal in the unsessions on day 2, if that'd work.

**Comment by VladUreche** [comment]
> That talk would be great. I'm not sure if I can commit to a joint talk, just because I'm planning on submitting a (lightning) talk on FpFilter and am already pressed for time with my 9 month old with another on the way :( (also :)). 

Wow, congratulations! Okay, then let's stick to a single miniboxing talk. Can you please update the blog post, so I can refer to it from the talk abstract? It may be better to use your vector example as the live demo instead of the streams library, as that's pretty difficult to explain.

> I'd probably be more up for doing something a little less formal in the unsessions on day 2, if that'd work.

Yep, that sounds good. But keep in mind I'll only come to nescala is my talk is accepted, because the plane tickets from Europe are very expensive. :(

**Comment by tixxit** [comment]
Yup, will update the blog post. May be a day or so though, since it's gotta go through someone else at work who actually formats them/posts them.

**Comment by VladUreche** [comment]
> Yup, will update the blog post. May be a day or so though, since it's gotta go through someone else at work who actually formats them/posts them.

Awesome, thanks! That will make a very cool motivation for the talk :)

**Pull request merged**
